name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'action.yml'
      - '.github/workflows/build.yml'

jobs:
  build:
    strategy:
      matrix:
        url:
          - "https://apps.apple.com/fr/app/youtube/id544007664"
        path:
          - YouTube.ipa
    runs-on: ubuntu-latest
    steps:
      - name: Download IPA
        uses: level3tjg/decryptedappstore-action@main
        with:
          appstore_url: "${{ matrix.url }}"
          cache: false
          path: ${{ matrix.path }}
          token: "${{ secrets.SESSION_TOKEN }}"

      - name: Check IPA was downloaded
        if: matrix.path != '' && hashFiles('YouTube.ipa') == ''
        run: exit 1
